### PR TITLE
Fix kit/hato module in modules.edn

### PR DESCRIPTION
**Pull request by jmarijano**
Add missing :kit/hato keyword in modules.edn

### CODE REVIEW

**Comment by yogthos** [comment]
good catch :)

**Comment by jmarijano** [comment]
I tried to install the hato module in a new project and was unpleasantly surprised when list-modules threw an exception. Let's just say that it was first-time contributor anxiety.

It looks like now list-modules works, and it seems that install hato also works, so I'm not sure if we can close [Issue #104](https://github.com/kit-clj/kit/issues/104)

**Comment by yogthos** [comment]
No worries, the good thing with modules is that it's easy to fix problems. I didn't notice the key was missing either when I merged, so mostly it's on me. :)

As a note, it's possible to test the modules locally when you develop them if you just make a fresh project and do `(kit/sync-modules)` from the REPL. It will make a `modules` folder in the project where this repo gets cloned and you can just modify stuff there and try it out. I should probably add a doc about that.

**Comment by jmarijano** [comment]
It would be great to have a doc for it, from a Clojure newbie perspective. Also, I will look in doc repository if I need to update some documentation regarding the newly added module. Thanks.

**Pull request merged**
